### PR TITLE
PROPOSAL: Adding bounding box instead of map-center / map-zoom

### PR DESCRIPTION
**Pull request by caryfitzhugh**
This is an API description change ONLY.  Before this is merged in, the map-viewer should implement the API and a release deployed to this branch.  This will ensure that any revision of the API on master will be functional.

Please comment +1 or something similar if you want to include this change.  Specifically the SUNY and Mann teams should comment.

### CODE REVIEW

**Comment by dbranchini** [comment]
Either implementation -- bounding box or map-center/map-zoom -- will work for us.

**Comment by bnoon** [comment]
I think the bbox works better.  I have a jsbin here that shows the difference: http://jsbin.com/guvise/edit?js,output

So +1 on the change.

**Comment by sasignell** [comment]
bbox is fine-- we just have to  clear on how to deliver it.  [Previously](http://frontierspatial.com/JanuarySprint/mapper/v1/), we've implemented order=W,S,E,N (lat/lon) which, I believe, is a standard OGC-compliant way of delivering bbox.  
However, leaflet uses a nested array of lat/lon for SW,NE, e.g. [[40.4959,-79.76338],[45.01605,-71.85616]] as Bill show in his jsbin example.  If we choose the former, we will have to do a bit of parsing before leaflet can use it, but that's no big deal.

**Comment by bnoon** [comment]
Good point Steve, I glossed over that.  I +1 using the standard W,S,E,N order (lon/lat or x/y pairs) no nesting.  That is what geoJSON uses for it's `bbox` attribute.

The transform to the leaflet nested `LatLon`'s is trivial.

**Comment by caryfitzhugh** [comment]
mussed that up. Should have put the new release on this PR. blerg.  well - fixing so it is the way it hsould be.

**Pull request merged**
